# Generated by Django 2.2 on 2020-11-07 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='interrupted',
        ),
    ]
